name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.team_50zQz5Dg17gwT2Lla8xZgdpn }}
  VERCEL_PROJECT_ID: ${{ secrets.lbpe9rgt6H73OjqWGyC9RFM9 }}
on:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.IAcYQGF2c8R6HTS4McLpQ8a3 }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.IAcYQGF2c8R6HTS4McLpQ8a3 }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.IAcYQGF2c8R6HTS4McLpQ8a3 }}
